server:
  port: 8080 # 内嵌的 Tomcat 端口号

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shomis?&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true # 是否显示sql语句
    generate-ddl: false # Whether to initialize the schema on startup.
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
